parser: 'babel-eslint'

extends:
  - 'react-app'
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'

plugins:
  - 'babel'
  - 'prettier'
  - 'mocha'

settings:
  react:
    version: 'detect'

env:
  browser: true
  mocha: true

rules:
  prettier/prettier:
    - 2
    - bracketSpacing: true
      singleQuote: true
      tabWidth: 2
      trailingComma: 'es5'
  no-lone-blocks: 0
  no-throw-literal: 0
  no-console: 0
  no-case-declarations: 0
  no-fallthrough: 0
  no-sparse-arrays: 0
  no-constant-condition: 0
  no-unused-vars:
    - 1
    - vars: 'local'
      varsIgnorePattern: '^G_'
