"use strict";

/**
 * IN2 Logic Tree File
 *
 * This file has been generated by an IN2 compiler.
 */

/*eslint-disable-line*/
function run(isDryRun) {
  /* global player, core, engine */
  var files = {};
  var scope = {};
  var CURRENT_NODE_VAR = 'curIN2n';
  var CURRENT_FILE_VAR = 'curIN2f';
  var LAST_FILE_VAR = 'lasIN2f';
  player.set('scope', scope);

  files["main.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'main.json');
    if (player.get('test') === undefined) player.set('test', 'value'); // action

    scope.p1O = function () {
      player.set(CURRENT_NODE_VAR, 'p1O');
      scope.CzA();
    }; // text


    scope.CzA = function () {
      player.set(CURRENT_NODE_VAR, 'CzA');
      var text = "The value of test is '".concat(player.get('test'), "'.");
      core.say(text, scope.Bf4, 'CzA', 'Bf4');
    }; // next_file


    scope.Bf4 = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "main.json";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    };

    if (id === undefined) {
      scope.p1O();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_Sol.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_Sol.json'); // next_file

    scope.tG08a = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    };

    if (id === undefined) {
      scope.tG08a();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_Idoreo.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_Idoreo.json'); // next_file

    scope.FdbAF = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    };

    if (id === undefined) {
      scope.FdbAF();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_Igmund.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_Igmund.json'); // next_file

    scope.iPi3f = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    };

    if (id === undefined) {
      scope.iPi3f();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_SchovanAbivola.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_SchovanAbivola.json'); // next_file

    scope.OhVgn = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    };

    if (id === undefined) {
      scope.OhVgn();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_RadmilaOmvaire.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_RadmilaOmvaire.json'); // next_file

    scope.KxZH3 = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    };

    if (id === undefined) {
      scope.KxZH3();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_GuardCaptainMullen.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_GuardCaptainMullen.json'); // switch

    scope.z81hnfzb9 = function () {
      player.set(CURRENT_NODE_VAR, 'z81hnfzb9');
      if (player.once()) scope.t92didcb6();else if (true) scope.fp58pmg2f();
    }; // text


    scope.t92didcb6 = function () {
      player.set(CURRENT_NODE_VAR, 't92didcb6');
      var text = "A young man man sits behind a large wooden desk here.  He wars a sash of green across his chest and a name plate on his desk says 'Guard Captain Mullen'. Below it is a small metal plaque 'in Realm service for 3 years'.  He pours over a complete mess of files on the tabletop, glancing quickly from one to the other, and doesn't seem to notice you as you approach.  Finally, after an uncomfortable silence he looks up at you.";
      core.say(text, scope.mxamfpggq, 't92didcb6', 'mxamfpggq');
    }; // text


    scope.mxamfpggq = function () {
      player.set(CURRENT_NODE_VAR, 'mxamfpggq');
      var text = "\"Ahh! Neither of the Nobility nor Merchantry.  A welcome respite.  What can I do for you?\"";
      core.say(text, scope.z30r19u3z, 'mxamfpggq', 'z30r19u3z');
    }; // choice


    scope.z30r19u3z = function () {
      player.set(CURRENT_NODE_VAR, 'z30r19u3z');
      var text = "";
      core.choose(text, 'z30r19u3z', [{
        t: "Who are you?",
        id: 'pwnhx499l',
        cb: scope.pwnhx499l,
        c: function c() {
          return true;
        }
      }, {
        t: "I've got some questions.",
        id: 'c4nwxzoao',
        cb: scope.c4nwxzoao,
        c: function c() {
          return true;
        }
      }, {
        t: "Nevermind.",
        id: 'F3tbm',
        cb: scope.F3tbm,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['z30r19u3z'].isChoice = true; // text

    scope.pwnhx499l = function () {
      player.set(CURRENT_NODE_VAR, 'pwnhx499l');
      var text = "\"Mullen.  Captain Mullen.  I am in command of the Realm forces in Alinea.\"  He gestures to the nameplate on his desk.";
      core.say(text, scope.z30r19u3z, 'pwnhx499l', 'z30r19u3z');
    }; // text


    scope.c4nwxzoao = function () {
      player.set(CURRENT_NODE_VAR, 'c4nwxzoao');
      var text = "\"Ask whatever you'd like.\"";
      core.say(text, scope.drkwr4h0c, 'c4nwxzoao', 'drkwr4h0c');
    }; // choice


    scope.drkwr4h0c = function () {
      player.set(CURRENT_NODE_VAR, 'drkwr4h0c');
      var text = "";
      core.choose(text, 'drkwr4h0c', [{
        t: "The Realm? What is that, exactly?",
        id: 'my1gp7aea',
        cb: scope.my1gp7aea,
        c: function c() {
          return true;
        }
      }, {
        t: "What can you tell me about Alinea?",
        id: 'gehdct87p',
        cb: scope.gehdct87p,
        c: function c() {
          return true;
        }
      }, {
        t: "What can you tell me of the Nobility?",
        id: 'mm89mf437',
        cb: scope.mm89mf437,
        c: function c() {
          return true;
        }
      }, {
        t: "It's hard to explain, but I'm looking for something, and all I have is a number: '9'.  Know anything?",
        id: 'ugxg25kzf',
        cb: scope.ugxg25kzf,
        c: function c() {
          return true;
        }
      }, {
        t: "Is there anything I can do for the Realm?",
        id: 'c6wfxaft9',
        cb: scope.c6wfxaft9,
        c: function c() {
          return true;
        }
      }, {
        t: "Let's talk about the Bandits.",
        id: 'ftsplrlgw',
        cb: scope.ftsplrlgw,
        c: function c() {
          return false && player.questInProgress('QUEST_AlineaBandits');
        }
      }, {
        t: "Lets talk about Lady Blackrose.",
        id: 'em5ywu7ud',
        cb: scope.em5ywu7ud,
        c: function c() {
          return false && player.questInProgress('QUEST_AlineaFindSpyRigby');
        }
      }, {
        t: "Nevermind, I'll be going now.",
        id: 'F3tbm',
        cb: scope.F3tbm,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['drkwr4h0c'].isChoice = true; // pass_fail

    scope.my1gp7aea = function () {
      player.set(CURRENT_NODE_VAR, 'my1gp7aea');

      var condition = function () {
        return player.once();
      }();

      if (condition) {
        player.set(CURRENT_NODE_VAR, 'c6464px3u');
        var text = "";
        core.say(text, scope.e0yuydu5n);
      }

      if (!condition) {
        player.set(CURRENT_NODE_VAR, 'f24zyyz3n');
        var _text = "";
        core.say(_text, scope.e4sbugei2);
      }
    }; // text


    scope.e0yuydu5n = function () {
      player.set(CURRENT_NODE_VAR, 'e0yuydu5n');
      var text = "He tilts his head to the side, confused, then his eyes widen as if seeing you for the first time.";
      core.say(text, scope.b9cc0nfn5, 'e0yuydu5n', 'b9cc0nfn5');
    }; // text


    scope.b9cc0nfn5 = function () {
      player.set(CURRENT_NODE_VAR, 'b9cc0nfn5');
      var text = "\"Ah, Yes.  A Lark.  Not to worry, I can explain. The Realm is the military force of the Mainland here on Sadelica.  King Treyborn has declared the island as part of the Mainland Empire, but in truth, he does not provide us enough resources to truly enforce that decree.\"  ";
      core.say(text, scope.e3adktxgc, 'b9cc0nfn5', 'e3adktxgc');
    }; // choice


    scope.e3adktxgc = function () {
      player.set(CURRENT_NODE_VAR, 'e3adktxgc');
      var text = "";
      core.choose(text, 'e3adktxgc', [{
        t: "So the Realm is the government here?",
        id: 'ky7xr01hi',
        cb: scope.ky7xr01hi,
        c: function c() {
          return true;
        }
      }, {
        t: "What can you tell me about the Order of Magi?",
        id: 'fi0gf7g8m',
        cb: scope.fi0gf7g8m,
        c: function c() {
          return player.get('nodes.od3u5s592');
        }
      }, {
        t: "Let's speak of something else.",
        id: 'xlru47a9p',
        cb: scope.xlru47a9p,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['e3adktxgc'].isChoice = true; // text

    scope.ky7xr01hi = function () {
      player.set(CURRENT_NODE_VAR, 'ky7xr01hi');
      var text = "\"Basically, yes.  But the fact of the matter is, we don't have all that much sway here on Sadelica.  Certain Nobles and Merchants have occupied the island with much more more agency than us.  And that's not even mentioning the Order of Magi...\"";
      core.say(text, scope.od3u5s592, 'ky7xr01hi', 'od3u5s592');
    }; // text


    scope.od3u5s592 = function () {
      player.set(CURRENT_NODE_VAR, 'od3u5s592');
      var text = "He gives a sheepish grin.  \"Quite frankly, calling ourselves part of the Mainland Empire would do a disservice to its might and power.  Instead we call ourselves 'The Realm' and we try to keep the peace around here.\"";
      core.say(text, scope.e3adktxgc, 'od3u5s592', 'e3adktxgc');
    }; // text


    scope.fi0gf7g8m = function () {
      player.set(CURRENT_NODE_VAR, 'fi0gf7g8m');
      var text = "He purses his lips.  \"A group which believes that Sadelica is their salvation.  They experiment with the magic here, and often cause critical problems for us.  I'd rather not speak of them.  They give me a headache.\"";
      core.say(text, scope.e3adktxgc, 'fi0gf7g8m', 'e3adktxgc');
    }; // text


    scope.xlru47a9p = function () {
      player.set(CURRENT_NODE_VAR, 'xlru47a9p');
      var text = "\"Indeed.\"";
      core.say(text, scope.drkwr4h0c, 'xlru47a9p', 'drkwr4h0c');
    }; // text


    scope.e4sbugei2 = function () {
      player.set(CURRENT_NODE_VAR, 'e4sbugei2');
      var text = "\"The Realm is the military force of the Mainland here on Sadelica.  The King has declared the island as part of the Mainland Empire, but in truth, he does not provide us enough resources to truly enforce that decree.\"";
      core.say(text, scope.e3adktxgc, 'e4sbugei2', 'e3adktxgc');
    }; // text


    scope.gehdct87p = function () {
      player.set(CURRENT_NODE_VAR, 'gehdct87p');
      var text = "\"It's port town, though a small one.  Bigger ports can be found at the northern and southern ends of Sadelica, so this place isn't particularly strategic.  But still, it's the place closest to the hinterlands in the northwest of Sadelica, so that makes it somewhat important for getting supplies there.\"";
      core.say(text, scope.drkwr4h0c, 'gehdct87p', 'drkwr4h0c');
    }; // text


    scope.mm89mf437 = function () {
      player.set(CURRENT_NODE_VAR, 'mm89mf437');
      var text = "\"There are quite a few nobles from the Mainland Empire who have staked their claims on Sadelica.  Some have more power than others, but of course gossip travels.  They all talk to each other.  They all know who's who and what's what.\"";
      core.say(text, scope.znt870yxb, 'mm89mf437', 'znt870yxb');
    }; // choice


    scope.znt870yxb = function () {
      player.set(CURRENT_NODE_VAR, 'znt870yxb');
      var text = "";
      core.choose(text, 'znt870yxb', [{
        t: "Anyone I should be on the lookout for?",
        id: 'xww6ih73f',
        cb: scope.xww6ih73f,
        c: function c() {
          return true;
        }
      }, {
        t: "Okay, enough about the Nobility.",
        id: 'x868igmqd',
        cb: scope.x868igmqd,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['znt870yxb'].isChoice = true; // text

    scope.xww6ih73f = function () {
      player.set(CURRENT_NODE_VAR, 'xww6ih73f');
      var text = "\"Well, Lord Guildimarche is probably the biggest one, but he hasn't expanded his power out here to Alinea yet.  I'm sure you'll find some of his brown-nosers though.\"";
      core.say(text, scope.ocfnyoge0, 'xww6ih73f', 'ocfnyoge0');
    }; // text


    scope.ocfnyoge0 = function () {
      player.set(CURRENT_NODE_VAR, 'ocfnyoge0');
      var text = "\"Other than that? I'm not sure.  My policy has always been to pay them as little attention as possible, until I can't avoid them anymore.\"";
      core.say(text, scope.znt870yxb, 'ocfnyoge0', 'znt870yxb');
    }; // text


    scope.x868igmqd = function () {
      player.set(CURRENT_NODE_VAR, 'x868igmqd');
      var text = "\"Indeed.\"";
      core.say(text, scope.drkwr4h0c, 'x868igmqd', 'drkwr4h0c');
    }; // text


    scope.ugxg25kzf = function () {
      player.set(CURRENT_NODE_VAR, 'ugxg25kzf');
      var text = "\"The number 9 huh?  Well, there are eight warehouses in Alinea, all owned by various members of the Merchantry or the Nobility.  There's actually a ninth though, but it's under disrepair and unavailable for use.   Maybe that's what you seek?\"";
      core.say(text, scope.iq5nw00dg, 'ugxg25kzf', 'iq5nw00dg');
    }; // choice


    scope.iq5nw00dg = function () {
      player.set(CURRENT_NODE_VAR, 'iq5nw00dg');
      var text = "";
      core.choose(text, 'iq5nw00dg', [{
        t: "What can you tell me about these warehouses?",
        id: 'gx1ehcd1o',
        cb: scope.gx1ehcd1o,
        c: function c() {
          return true;
        }
      }, {
        t: "There's a 9th warehouse in Alinea?",
        id: 'dw8pkpyst',
        cb: scope.dw8pkpyst,
        c: function c() {
          return true;
        }
      }, {
        t: "Is there any way for me to get inside the ninth warehouse?",
        id: 'f3ucg04ey',
        cb: scope.f3ucg04ey,
        c: function c() {
          return true;
        }
      }, {
        t: "Let's speak of something else.",
        id: 'y2f6s4el1',
        cb: scope.y2f6s4el1,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['iq5nw00dg'].isChoice = true; // text

    scope.gx1ehcd1o = function () {
      player.set(CURRENT_NODE_VAR, 'gx1ehcd1o');
      var text = "\"Well, Alinea is a port, so it's advantageous for one to own a warehouse here.  Ships come in, sell there wares to merchants and those merchants store the goods in a warehouse.  Traders come along and take these goods to all other parts of Sadelica.  You can turn a tidy profit with a business like that.  All the warehouses here are owned by a member of the Merchantry.\"";
      core.say(text, scope.iq5nw00dg, 'gx1ehcd1o', 'iq5nw00dg');
    }; // text


    scope.dw8pkpyst = function () {
      player.set(CURRENT_NODE_VAR, 'dw8pkpyst');
      var text = "\"Yes.  It's on the far east of town.  Locked though.  Nobody really knows who owns it.  Nobody's been over there for quite a long time.\"";
      core.say(text, scope.iq5nw00dg, 'dw8pkpyst', 'iq5nw00dg');
    }; // text


    scope.f3ucg04ey = function () {
      player.set(CURRENT_NODE_VAR, 'f3ucg04ey');
      var text = "\"I doubt it.  That warehouse hasn't been used in a long time.  Although you might have some luck talking to some of the Merchantry folks about it. They've been scoping out the place for a while now and might have more information than me.\"";
      core.say(text, scope.iq5nw00dg, 'f3ucg04ey', 'iq5nw00dg');
    }; // text


    scope.y2f6s4el1 = function () {
      player.set(CURRENT_NODE_VAR, 'y2f6s4el1');
      var text = "\"Indeed.\"";
      core.say(text, scope.drkwr4h0c, 'y2f6s4el1', 'drkwr4h0c');
    }; // pass_fail


    scope.c6wfxaft9 = function () {
      player.set(CURRENT_NODE_VAR, 'c6wfxaft9');

      var condition = function () {
        return player.once() ? true : false;
      }();

      if (condition) {
        player.set(CURRENT_NODE_VAR, 'imgg1wnfx');
        var text = "";
        core.say(text, scope.lplgcudfx);
      }

      if (!condition) {
        player.set(CURRENT_NODE_VAR, 'rbeclwg25');
        var _text2 = "";
        core.say(_text2, scope.gf5514fm8);
      }
    }; // text


    scope.lplgcudfx = function () {
      player.set(CURRENT_NODE_VAR, 'lplgcudfx');
      var text = "Captain Mullen's raises an eyebrow.  \"Well, if you're not opposed to some dangerous work... we have two significant problems.  One regarding Bandits, and one regarding Lady Blackrose\"";
      core.say(text, scope.qd80fht5l, 'lplgcudfx', 'qd80fht5l');
    }; // choice


    scope.qd80fht5l = function () {
      player.set(CURRENT_NODE_VAR, 'qd80fht5l');
      var text = "";
      core.choose(text, 'qd80fht5l', [{
        t: "Tell me about the Bandits.",
        id: 's7ol4sapp',
        cb: scope.s7ol4sapp,
        c: function c() {
          return player.once();
        }
      }, {
        t: "Tell me about Lady Blackrose.",
        id: 'lsymg41b0',
        cb: scope.lsymg41b0,
        c: function c() {
          return player.once();
        }
      }, {
        t: "Actually, let's talk about something else.",
        id: 'x868igmqd',
        cb: scope.x868igmqd,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['qd80fht5l'].isChoice = true; // text

    scope.s7ol4sapp = function () {
      player.set(CURRENT_NODE_VAR, 's7ol4sapp');
      var text = "\"There are some Bandits blocking the road north.  It's actually becoming a significant problem. There are quite a few of them, and I don't have enough soldiers here to show a big enough force to intimidate them to leave, so I'm forced to wait for reinforcements.\"  He grimaces. \"Those are... potentially several days away.\"";
      core.say(text, scope.p3cfkcdas, 's7ol4sapp', 'p3cfkcdas');
    }; // text


    scope.p3cfkcdas = function () {
      player.set(CURRENT_NODE_VAR, 'p3cfkcdas');
      var text = "\"If possible, I'd like to resolve this peacefully.  if somebody would go in as a liaison and talk to them, see if they have any demands, see if they can be reasoned with, then maybe I can negotiate some terms until my reinforcements come.\"";
      core.say(text, scope.yfi3xqx1g, 'p3cfkcdas', 'yfi3xqx1g');
    }; // choice


    scope.yfi3xqx1g = function () {
      player.set(CURRENT_NODE_VAR, 'yfi3xqx1g');
      var text = "";
      core.choose(text, 'yfi3xqx1g', [{
        t: "And you think I could do this?",
        id: 'idgxllf69',
        cb: scope.idgxllf69,
        c: function c() {
          return true;
        }
      }, {
        t: "I guess I could go check it out, for a price.",
        id: 'ltgftwh3h',
        cb: scope.ltgftwh3h,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['yfi3xqx1g'].isChoice = true; // text

    scope.idgxllf69 = function () {
      player.set(CURRENT_NODE_VAR, 'idgxllf69');
      var text = "\"I mean, yeah, it will be dangerous, but you don't have any allegiances here.  You're a third party.  They might not attack you on sight like they have been doing to my men.\"";
      core.say(text, scope.dqb7zka4b, 'idgxllf69', 'dqb7zka4b');
    }; // action


    scope.dqb7zka4b = function () {
      player.set(CURRENT_NODE_VAR, 'dqb7zka4b');
      player.startQuest('QUEST_AlineaBandits');
      scope.te184lirt();
    }; // choice


    scope.te184lirt = function () {
      player.set(CURRENT_NODE_VAR, 'te184lirt');
      var text = "";
      core.choose(text, 'te184lirt', [{
        t: "How long have the Bandits been there?",
        id: 'ct0cluu5q',
        cb: scope.ct0cluu5q,
        c: function c() {
          return true;
        }
      }, {
        t: "I've spoken to the bandits.  They have some demands.",
        id: 'cqf7behx0',
        cb: scope.cqf7behx0,
        c: function c() {
          return questStepEQ('QUEST_AlineaBandits', 1);
        }
      }, {
        t: "Actually, nevermind.  Let's talk about something else.",
        id: 'q6ypuxn6i',
        cb: scope.q6ypuxn6i,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['te184lirt'].isChoice = true; // text

    scope.ct0cluu5q = function () {
      player.set(CURRENT_NODE_VAR, 'ct0cluu5q');
      var text = "\"For almost a month, they've been attacking trade caravans going up there.  But they've only outright blocked the road for a week.\"";
      core.say(text, scope.lo9f52464, 'ct0cluu5q', 'lo9f52464');
    }; // text


    scope.lo9f52464 = function () {
      player.set(CURRENT_NODE_VAR, 'lo9f52464');
      var text = "\"If something isn't done about them soon, we might not be able to get supplies up north to the hinterlands, and that would spell disaster for any settlements there.\"";
      core.say(text, scope.te184lirt, 'lo9f52464', 'te184lirt');
    }; // text


    scope.cqf7behx0 = function () {
      player.set(CURRENT_NODE_VAR, 'cqf7behx0');
      var text = "\"They do, do they?  What might those demands be?\"";
      core.say(text, scope.wme4f810n, 'cqf7behx0', 'wme4f810n');
    }; // choice


    scope.wme4f810n = function () {
      player.set(CURRENT_NODE_VAR, 'wme4f810n');
      var text = "";
      core.choose(text, 'wme4f810n', [{
        t: "Apparently they are exiled Nobility. They want to be reinstated.",
        id: 'us7hb1q6f',
        cb: scope.us7hb1q6f,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['wme4f810n'].isChoice = true; // text

    scope.us7hb1q6f = function () {
      player.set(CURRENT_NODE_VAR, 'us7hb1q6f');
      var text = "Captain Mullen whistles softly.  \"Do they now?  That's, not going to go over well.  No not well at all.\"";
      core.say(text, scope.tbdd3aok5, 'us7hb1q6f', 'tbdd3aok5');
    }; // choice


    scope.tbdd3aok5 = function () {
      player.set(CURRENT_NODE_VAR, 'tbdd3aok5');
      var text = "";
      core.choose(text, 'tbdd3aok5', [{
        t: "What do you mean?",
        id: 'mgbazf8c2',
        cb: scope.mgbazf8c2,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['tbdd3aok5'].isChoice = true; // text

    scope.mgbazf8c2 = function () {
      player.set(CURRENT_NODE_VAR, 'mgbazf8c2');
      var text = "\"The only person with enough influence to do that around her is Lady Blackrose, and I'm wont to ask her for any favors.\"";
      core.say(text, scope.nlaeazhoq, 'mgbazf8c2', 'nlaeazhoq');
    }; // choice


    scope.nlaeazhoq = function () {
      player.set(CURRENT_NODE_VAR, 'nlaeazhoq');
      var text = "";
      core.choose(text, 'nlaeazhoq', [{
        t: "I see.  Well it can't hurt to try, can it?",
        id: 'ie1t20w5m',
        cb: scope.ie1t20w5m,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['nlaeazhoq'].isChoice = true; // text

    scope.ie1t20w5m = function () {
      player.set(CURRENT_NODE_VAR, 'ie1t20w5m');
      var text = "\"I suppose not, but I don't want to be the one that does it.\"  He gives a you a pointed stare.";
      core.say(text, scope.rhzs96c43, 'ie1t20w5m', 'rhzs96c43');
    }; // choice


    scope.rhzs96c43 = function () {
      player.set(CURRENT_NODE_VAR, 'rhzs96c43');
      var text = "";
      core.choose(text, 'rhzs96c43', [{
        t: "Fine, I'll as Lady Blackrose about this.  But you owe me.",
        id: 'clenli1mf',
        cb: scope.clenli1mf,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['rhzs96c43'].isChoice = true; // text

    scope.clenli1mf = function () {
      player.set(CURRENT_NODE_VAR, 'clenli1mf');
      var text = "\"Of course, of course.\"  He reaches into his desk and throws you a bag of coins.  \"For your effort.\"";
      core.say(text, scope.th5h36fp2, 'clenli1mf', 'th5h36fp2');
    }; // action


    scope.th5h36fp2 = function () {
      player.set(CURRENT_NODE_VAR, 'th5h36fp2');
      player.completeQuestStep('QUEST_AlineaBandits', 3);
      scope.fe8kiyl33();
    }; // next_file


    scope.fe8kiyl33 = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    }; // text


    scope.q6ypuxn6i = function () {
      player.set(CURRENT_NODE_VAR, 'q6ypuxn6i');
      var text = "\"Indeed.\"";
      core.say(text, scope.drkwr4h0c, 'q6ypuxn6i', 'drkwr4h0c');
    }; // text


    scope.ltgftwh3h = function () {
      player.set(CURRENT_NODE_VAR, 'ltgftwh3h');
      var text = "\"I'd never expect somebody to do that for free.  If you can get rid of the Bandits, then I'd be very much in your debt actually.  Trust me, I'll make it worth your while.\"";
      core.say(text, scope.idgxllf69, 'ltgftwh3h', 'idgxllf69');
    }; // text


    scope.lsymg41b0 = function () {
      player.set(CURRENT_NODE_VAR, 'lsymg41b0');
      var text = "\"A very high-up member of the Nobility has come to Alinea recently.  Her name is Lady Aldebeth Blackrose, and she's brought a rather sizable contingent of soldiers.  They're camped out just to the east of town.  Apparently she wants to build Alinea out into a haven for her house, but I'm not so sure she doesn't mean to conquer the place.\"";
      core.say(text, scope.oxa71xu1r, 'lsymg41b0', 'oxa71xu1r');
    }; // text


    scope.oxa71xu1r = function () {
      player.set(CURRENT_NODE_VAR, 'oxa71xu1r');
      var text = "\"I've enlisted a spy into the Blackrose ranks.  Her name is Rigby.  I need somebody unaffiliated with me to take messages back and forth between her and I.  Interested?\"";
      core.say(text, scope.gdxha6smq, 'oxa71xu1r', 'gdxha6smq');
    }; // choice


    scope.gdxha6smq = function () {
      player.set(CURRENT_NODE_VAR, 'gdxha6smq');
      var text = "";
      core.choose(text, 'gdxha6smq', [{
        t: "Lady Blackrose wishes to conquer Alinea?",
        id: 'fw3110gl5',
        cb: scope.fw3110gl5,
        c: function c() {
          return true;
        }
      }, {
        t: "I suppose could help you, if you paid me.",
        id: 'o5k8qdr0e',
        cb: scope.o5k8qdr0e,
        c: function c() {
          return true;
        }
      }, {
        t: "Sure, I'd love to lend aid to the Realm.",
        id: 'ouefwhzsz',
        cb: scope.ouefwhzsz,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['gdxha6smq'].isChoice = true; // text

    scope.fw3110gl5 = function () {
      player.set(CURRENT_NODE_VAR, 'fw3110gl5');
      var text = "\"Perhaps conquer is too harsh.  But if Lady Blackrose were to *replace* the Realm garrisoned here with the forces she brought, then she would have an awful lot of say over the port.\"";
      core.say(text, scope.n7hkkt5gw, 'fw3110gl5', 'n7hkkt5gw');
    }; // choice


    scope.n7hkkt5gw = function () {
      player.set(CURRENT_NODE_VAR, 'n7hkkt5gw');
      var text = "";
      core.choose(text, 'n7hkkt5gw', [{
        t: "Isn't that illegal?  Wouldn't the Realm take issue with that?\"",
        id: 'i5ctqpcbn',
        cb: scope.i5ctqpcbn,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['n7hkkt5gw'].isChoice = true; // text

    scope.i5ctqpcbn = function () {
      player.set(CURRENT_NODE_VAR, 'i5ctqpcbn');
      var text = "\"We would if we had enough power to contend with the Nobility, but... alas.\"  He spreads his hands sheepishly.  \"Of course she hasn't actually done anything yet, so I can't even file a formal complaint.\"";
      core.say(text, scope.gdxha6smq, 'i5ctqpcbn', 'gdxha6smq');
    }; // text


    scope.o5k8qdr0e = function () {
      player.set(CURRENT_NODE_VAR, 'o5k8qdr0e');
      var text = "\"Yes yes, of course I'd pay you.  Per message.  One-way.\"";
      core.say(text, scope.ouefwhzsz, 'o5k8qdr0e', 'ouefwhzsz');
    }; // text


    scope.ouefwhzsz = function () {
      player.set(CURRENT_NODE_VAR, 'ouefwhzsz');
      var text = "\"You'll have to find Rigby in the Blackrose camp out to the east side of town.  For goodness sakes, don't ask around for here - that's too conspicuous - but if you spend enough time there I'm sure she'll approach you on her own.  She is quite sharp.\"";
      core.say(text, scope.pr2rne1fh, 'ouefwhzsz', 'pr2rne1fh');
    }; // choice


    scope.pr2rne1fh = function () {
      player.set(CURRENT_NODE_VAR, 'pr2rne1fh');
      var text = "";
      core.choose(text, 'pr2rne1fh', [{
        t: "I found Rigby. She gave me a message for you.",
        id: 'f3m3mg3oe',
        cb: scope.f3m3mg3oe,
        c: function c() {
          return questStepEQ('QUEST_AlineaSpyRigby', 1);
        }
      }, {
        t: "Actually, nevermind.  Let's talk about something else.",
        id: 'i23bcc8al',
        cb: scope.i23bcc8al,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['pr2rne1fh'].isChoice = true; // text

    scope.f3m3mg3oe = function () {
      player.set(CURRENT_NODE_VAR, 'f3m3mg3oe');
      var text = "He takes the sealed envelope, flips it open and reads the contents.  A frown creases on his forehead as he does so, and when he finishes he slowly puts the paper down on his desk.";
      core.say(text, scope.nfily548m, 'f3m3mg3oe', 'nfily548m');
    }; // text


    scope.nfily548m = function () {
      player.set(CURRENT_NODE_VAR, 'nfily548m');
      var text = "\"Unwelcome news.\"";
      core.say(text, scope.kgcs05i98, 'nfily548m', 'kgcs05i98');
    }; // choice


    scope.kgcs05i98 = function () {
      player.set(CURRENT_NODE_VAR, 'kgcs05i98');
      var text = "";
      core.choose(text, 'kgcs05i98', [{
        t: "Anything I can do to help?",
        id: 'o76mg998o',
        cb: scope.o76mg998o,
        c: function c() {
          return true;
        }
      }, {
        t: "Huh?",
        id: 'tb071psl6',
        cb: scope.tb071psl6,
        c: function c() {
          return true;
        }
      }, {
        t: "Let's talk about something else.",
        id: 'i23bcc8al',
        cb: scope.i23bcc8al,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['kgcs05i98'].isChoice = true; // text

    scope.o76mg998o = function () {
      player.set(CURRENT_NODE_VAR, 'o76mg998o');
      var text = "\"No, nothing at all.\"";
      core.say(text, scope.kgcs05i98, 'o76mg998o', 'kgcs05i98');
    }; // text


    scope.tb071psl6 = function () {
      player.set(CURRENT_NODE_VAR, 'tb071psl6');
      var text = "\"Huh?\"";
      core.say(text, scope.kgcs05i98, 'tb071psl6', 'kgcs05i98');
    }; // text


    scope.i23bcc8al = function () {
      player.set(CURRENT_NODE_VAR, 'i23bcc8al');
      var text = "\"Indeed.\"";
      core.say(text, scope.drkwr4h0c, 'i23bcc8al', 'drkwr4h0c');
    }; // text


    scope.gf5514fm8 = function () {
      player.set(CURRENT_NODE_VAR, 'gf5514fm8');
      var text = "\"We have two significant problems.  One regarding Bandits, and one regarding Lady Blackrose.\"";
      core.say(text, scope.qd80fht5l, 'gf5514fm8', 'qd80fht5l');
    }; // text


    scope.ftsplrlgw = function () {
      player.set(CURRENT_NODE_VAR, 'ftsplrlgw');
      var text = "\"I'm all ears.  What can you tell me?\"";
      core.say(text, scope.te184lirt, 'ftsplrlgw', 'te184lirt');
    }; // text


    scope.em5ywu7ud = function () {
      player.set(CURRENT_NODE_VAR, 'em5ywu7ud');
      var text = "\"You have a message for me?\"";
      core.say(text, scope.pr2rne1fh, 'em5ywu7ud', 'pr2rne1fh');
    }; // next_file


    scope.F3tbm = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    }; // text


    scope.fp58pmg2f = function () {
      player.set(CURRENT_NODE_VAR, 'fp58pmg2f');
      var text = "\"Hello again.\" ";
      core.say(text, scope.z30r19u3z, 'fp58pmg2f', 'z30r19u3z');
    };

    if (id === undefined) {
      scope.z81hnfzb9();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_Gruff.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_Gruff.json'); // next_file

    scope.f1zni = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    };

    if (id === undefined) {
      scope.f1zni();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_Elvyosa.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_Elvyosa.json'); // next_file

    scope.m8Gsl = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    };

    if (id === undefined) {
      scope.m8Gsl();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_DunnsMurose.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_DunnsMurose.json'); // next_file

    scope.YDiFN = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    };

    if (id === undefined) {
      scope.YDiFN();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_Chem.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_Chem.json'); // next_file

    scope.RLgZd = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    };

    if (id === undefined) {
      scope.RLgZd();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_DockmasterClaire.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_DockmasterClaire.json'); // switch

    scope.G2sLG = function () {
      player.set(CURRENT_NODE_VAR, 'G2sLG');
      if (player.once()) scope.XgRzi();else if (true) scope.BgtJr();
    }; // text


    scope.XgRzi = function () {
      player.set(CURRENT_NODE_VAR, 'XgRzi');
      var text = "A stern woman, clipboard in hand, oversees the workers bustling about the docks.  She barks orders with every other breath, gesturing curtly with bony fingers and an icy glare.  A bright green tabard marks her as a Realm Adjutant.  Your approach hardly gives her pause.";
      core.say(text, scope.BgtJr, 'XgRzi', 'BgtJr');
    }; // text


    scope.BgtJr = function () {
      player.set(CURRENT_NODE_VAR, 'BgtJr');
      var text = "\"What is it?  What do you need?\"";
      core.say(text, scope.qlRtQ, 'BgtJr', 'qlRtQ');
    }; // choice


    scope.qlRtQ = function () {
      player.set(CURRENT_NODE_VAR, 'qlRtQ');
      var text = "";
      core.choose(text, 'qlRtQ', [{
        t: "Who are you?",
        id: 'DERfp',
        cb: scope.DERfp,
        c: function c() {
          return true;
        }
      }, {
        t: "What are \"Larks\"?",
        id: 'Y5uuR',
        cb: scope.Y5uuR,
        c: function c() {
          return player.get('nodes.DERfp');
        }
      }, {
        t: "Nevermind.",
        id: 'w1b5S',
        cb: scope.w1b5S,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['qlRtQ'].isChoice = true; // text

    scope.DERfp = function () {
      player.set(CURRENT_NODE_VAR, 'DERfp');
      var text = "She spits at the ground.  \"Faw!  Larks!  As clueless as ever I see.\"";
      core.say(text, scope.Ip8B3, 'DERfp', 'Ip8B3');
    }; // text


    scope.Ip8B3 = function () {
      player.set(CURRENT_NODE_VAR, 'Ip8B3');
      var text = "She points at her tabard as if that was self-explanitory.  \"I'm Claire.  Dock Master here in Alinea.  That means try to behave when I'm around or I'll have to send you into seclusion.  Had a few troublemakers just yesterday, thought they could sneak a few shipments of shelk into warehouse 3.\"  She shakes her head in disappointment.  \"I'd feel bad for them if I hadn't seen the like a hundred times over.\"";
      core.say(text, scope.qlRtQ, 'Ip8B3', 'qlRtQ');
    }; // text


    scope.Y5uuR = function () {
      player.set(CURRENT_NODE_VAR, 'Y5uuR');
      var text = "\"It means you're new here.  Get used to that label.  You're the Larkiest Larks I've ever seen.\"";
      core.say(text, scope.qlRtQ, 'Y5uuR', 'qlRtQ');
    }; // next_file


    scope.w1b5S = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    };

    if (id === undefined) {
      scope.G2sLG();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_BartoloCaldeburn.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_BartoloCaldeburn.json'); // switch

    scope.enWMm = function () {
      player.set(CURRENT_NODE_VAR, 'enWMm');
      if (player.once()) scope.mqogS();else if (true) scope.SwzEw();
    }; // text


    scope.mqogS = function () {
      player.set(CURRENT_NODE_VAR, 'mqogS');
      var text = "A nobleman sits here, his clothes notably more gaudy and pretentious than anyone else around.  A deep blue lace lines every possible edge of his silk coat, and auburn trousers glint with a distracting sheen.  He clasps a large glass of plum wine and idly taps a finger on the rough wood of the table.  He ignores the other patrons in the room as his gaze passes imperiously by them to rest upon you.";
      core.say(text, scope.dY7sz, 'mqogS', 'dY7sz');
    }; // text


    scope.dY7sz = function () {
      player.set(CURRENT_NODE_VAR, 'dY7sz');
      var text = "\"And what have we here?  Another rabble come to further dissuade me from this pit of a town?\"";
      core.say(text, scope.ku2iV, 'dY7sz', 'ku2iV');
    }; // choice


    scope.ku2iV = function () {
      player.set(CURRENT_NODE_VAR, 'ku2iV');
      var text = "";
      core.choose(text, 'ku2iV', [{
        t: "Who are you?",
        id: 'ASqD8',
        cb: scope.ASqD8,
        c: function c() {
          return true;
        }
      }, {
        t: "Don't like Alinea much?",
        id: 'zkasm',
        cb: scope.zkasm,
        c: function c() {
          return true;
        }
      }, {
        t: "You work for Lord Guildimarche?  Who is that?",
        id: 'ecss2',
        cb: scope.ecss2,
        c: function c() {
          return player.get('nodes.ASqD8');
        }
      }, {
        t: "What is someone as 'esteemed' as you doing here?",
        id: 'KLPVt',
        cb: scope.KLPVt,
        c: function c() {
          return player.get('nodes.ASqD8');
        }
      }, {
        t: "Idle threats?  Are you always this distasteful?",
        id: 'DRtxf',
        cb: scope.DRtxf,
        c: function c() {
          return player.get('nodes.OfySb');
        }
      }, {
        t: "There are bandits to the north?",
        id: 'wEid3',
        cb: scope.wEid3,
        c: function c() {
          return player.get('nodes.KLPVt');
        }
      }, {
        t: "Nevermind.",
        id: 'udfI0',
        cb: scope.udfI0,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['ku2iV'].isChoice = true; // text

    scope.ASqD8 = function () {
      player.set(CURRENT_NODE_VAR, 'ASqD8');
      var text = "\"Lord Bartolo Caldeburn, originally of the Esthsmund Estates.  You've heard of those?\"";
      core.say(text, scope.p7wcf, 'ASqD8', 'p7wcf');
    }; // choice


    scope.p7wcf = function () {
      player.set(CURRENT_NODE_VAR, 'p7wcf');
      var text = "";
      core.choose(text, 'p7wcf', [{
        t: "Nope.",
        id: 'tE4LF',
        cb: scope.tE4LF,
        c: function c() {
          return true;
        }
      }, {
        t: "It kind of rings a bell I suppose...",
        id: 'tE4LF',
        cb: scope.tE4LF,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['p7wcf'].isChoice = true; // text

    scope.tE4LF = function () {
      player.set(CURRENT_NODE_VAR, 'tE4LF');
      var text = "\"Yes well... They are renowned on the Mainland for their luxury.  I suppose simpletons such as yourselves would not understand.  Suffice to say that I am important.  Very important.  You should certainly not underestimate that fact.  These days I lend my assistance to Lord Guildimarche and his grand estate.\"";
      core.say(text, scope.ku2iV, 'tE4LF', 'ku2iV');
    }; // text


    scope.zkasm = function () {
      player.set(CURRENT_NODE_VAR, 'zkasm');
      var text = "\"Certainly not!  The people here no nothing of luxury.  They they think only in singles.\" He taps his glass. \"A mere single selection of wine, a single bed, a single tavern...  How can a man visit this town with anything but disappointment?\"";
      core.say(text, scope.gIcZc, 'zkasm', 'gIcZc');
    }; // text


    scope.gIcZc = function () {
      player.set(CURRENT_NODE_VAR, 'gIcZc');
      var text = "\"The only thing I can say for sure that it has is plenty of Larks.\"  He makes a shooing gesture at you.";
      core.say(text, scope.ku2iV, 'gIcZc', 'ku2iV');
    }; // text


    scope.ecss2 = function () {
      player.set(CURRENT_NODE_VAR, 'ecss2');
      var text = "Lord Cladeburn's face contorts into an aghast expression.";
      core.say(text, scope.GM0EE, 'ecss2', 'GM0EE');
    }; // text


    scope.GM0EE = function () {
      player.set(CURRENT_NODE_VAR, 'GM0EE');
      var text = "\"I do not 'work for' Lord Guildimarche, as you so uncouthly put it.  We are of the noble persuasion, we do favors for each other.  We lend aid!\"  ";
      core.say(text, scope.ViWA8, 'GM0EE', 'ViWA8');
    }; // text


    scope.ViWA8 = function () {
      player.set(CURRENT_NODE_VAR, 'ViWA8');
      var text = "\"It just so happens that the Guildimarche estate has quite the pull on Sadelica.  Save for Alinea and perhaps the Magi Tower, go most anywhere on this accursed island and you'll find some establishment associated with that name.  This is not a coincidence.  Perhaps *you* would not know of such things, but support for such a strong house tends to bear fruit.\"";
      core.say(text, scope.ku2iV, 'ViWA8', 'ku2iV');
    }; // text


    scope.KLPVt = function () {
      player.set(CURRENT_NODE_VAR, 'KLPVt');
      var text = "\"I am waiting for the Bandits currently occupying the northern bridge to be dealt with.  Then I can safety return to a place of at least relative sanity.\"";
      core.say(text, scope.OfySb, 'KLPVt', 'OfySb');
    }; // text


    scope.OfySb = function () {
      player.set(CURRENT_NODE_VAR, 'OfySb');
      var text = "\"And might I advise you to watch your tone, or you might find your tongue in a ditch somewhere.\"";
      core.say(text, scope.CfFBg, 'OfySb', 'CfFBg');
    }; // text


    scope.CfFBg = function () {
      player.set(CURRENT_NODE_VAR, 'CfFBg');
      var text = "He takes a small sip from his drink, and you notice a wickedly curved blade on a hilt at his hip.";
      core.say(text, scope.ku2iV, 'CfFBg', 'ku2iV');
    }; // text


    scope.DRtxf = function () {
      player.set(CURRENT_NODE_VAR, 'DRtxf');
      var text = "\"Like most reasonable people, I do not suffer fools.\"";
      core.say(text, scope.ku2iV, 'DRtxf', 'ku2iV');
    }; // text


    scope.wEid3 = function () {
      player.set(CURRENT_NODE_VAR, 'wEid3');
      var text = "\"Yes there are, and they have been quite the nuisance.  I'm simply waiting for them to be dealt with.  It is only a matter of time.\"";
      core.say(text, scope.ku2iV, 'wEid3', 'ku2iV');
    }; // next_file


    scope.udfI0 = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    }; // text


    scope.SwzEw = function () {
      player.set(CURRENT_NODE_VAR, 'SwzEw');
      var text = "\"Back again I see...\"";
      core.say(text, scope.ku2iV, 'SwzEw', 'ku2iV');
    };

    if (id === undefined) {
      scope.enWMm();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_SirLavolanChevel.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_SirLavolanChevel.json'); // next_file

    scope.r7TWk = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    };

    if (id === undefined) {
      scope.r7TWk();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_Scopey.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_Scopey.json'); // next_file

    scope.bUbbt = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    };

    if (id === undefined) {
      scope.bUbbt();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_AldebethBlackrose.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_AldebethBlackrose.json'); // switch

    scope.xn4GD = function () {
      player.set(CURRENT_NODE_VAR, 'xn4GD');
      if (player.once()) scope.Ck2ff();else if (true) scope.sBfVM();
    }; // text


    scope.Ck2ff = function () {
      player.set(CURRENT_NODE_VAR, 'Ck2ff');
      var text = "The leader of the mercenary company occupying these red tents is obviously the woman standing in front of you. Elegant and aristocratic, her exquisite silk dress is slashed with the the white and red of what is very clearly the Blackrose crest, her hair cascades down her back in a bevy of intricate curls, and a fashionable high-neck collar accentuates her ample bosom.  ";
      core.say(text, scope.niNF7, 'Ck2ff', 'niNF7');
    }; // choice


    scope.niNF7 = function () {
      player.set(CURRENT_NODE_VAR, 'niNF7');
      var text = "";
      core.choose(text, 'niNF7', [{
        t: "Who are you?",
        id: 'R3DD4',
        cb: scope.R3DD4,
        c: function c() {
          return true;
        }
      }, {
        t: "Blackrose LEGION!?  How many of you are there?",
        id: 'ceRC2',
        cb: scope.ceRC2,
        c: function c() {
          return player.get('nodes.R3DD4');
        }
      }, {
        t: "Nevermind.",
        id: 'QUeaf',
        cb: scope.QUeaf,
        c: function c() {
          return true;
        }
      }]);
    };

    scope['niNF7'].isChoice = true; // text

    scope.R3DD4 = function () {
      player.set(CURRENT_NODE_VAR, 'R3DD4');
      var text = "She raises a thinly-painted eyebrow.  \"I am Lady Aldebeth Blackrose.  I lead this contingent of the great Blackrose legion.\"";
      core.say(text, scope.niNF7, 'R3DD4', 'niNF7');
    }; // text


    scope.ceRC2 = function () {
      player.set(CURRENT_NODE_VAR, 'ceRC2');
      var text = "Her lips curl into a slight smile.  \"We are indeed, a great military force, renowned, and dare I say \"feared\" throughout Sadelica.  You should contain your awe better, it is unbecoming for any person to show such raw emotion in mundane moments such as this.\"";
      core.say(text, scope.niNF7, 'ceRC2', 'niNF7');
    }; // next_file


    scope.QUeaf = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "none";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    }; // text


    scope.sBfVM = function () {
      player.set(CURRENT_NODE_VAR, 'sBfVM');
      var text = "\"Ah yes.  You.  What is it you want this time?\"";
      core.say(text, scope.niNF7, 'sBfVM', 'niNF7');
    };

    if (id === undefined) {
      scope.xn4GD();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files["Alinea_CH_SpyRigby.json"] = function (id) {
    player.set(CURRENT_FILE_VAR, 'Alinea_CH_SpyRigby.json'); // next_file

    scope.Hg9db = function () {
      player.set(LAST_FILE_VAR, player.get(CURRENT_FILE_VAR));
      var key = "NONE";
      var func = files[key];

      if (func) {
        func();
      } else {
        core.exit();
      }
    };

    if (id === undefined) {
      scope.Hg9db();
    } else if (id) {
      scope[id]();
    }

    return player.state;
  };

  files.exit = function () {
    core.exit();
  };

  if (!isDryRun) {
    files['main.json']();
  }

  return {
    files: files,
    scope: scope
  };
}
